POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "DexterLakin",
  "author": "Dexter Lakin",
  "url": "https://dexterlakin.com/",
  "likes": 0,
  "userId": "60b3c40a1cf74466d2772d81"
}
